
version: "3.5"


services:

  nginx:
    depends_on:
      - app
    image: nginx:1.19-alpine
    container_name: nginx
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    logging:
      driver: "none"
    # restart: always 

  # 
  #  Backend API
  #
  app:
    depends_on:
      - postgresql
    image: node:18-alpine
    container_name: app
    environment: 
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=xray
      - DB_PASSWORD=root
      - DB_USERNAME=root
    working_dir: /app 
    volumes: 
        - ./app:/app
    ports:
      - 5000:5000        
    command: npm run start
    # restart: on-failure


  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: -p 5432 -c log_statement=all
    environment:
      - POSTGRES_DB=xray
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
